export const CURRENT_PROJECT = "CURRENT_PROJECT";

export const CURRENT_PROJECT_PATH = "CURRENT_PROJECT_PATH";

export const CURRENT_EDITOR_TABS = "CURRENT_EDITOR_TABS";

export const REMOVE_CURRENT_EDITOR_TAB = "REMOVE_CURRENT_EDITOR_TAB";